export { default as bookCover } from "./book.jpg"
export { default as defaultUser } from "./default_icon.jpg"

export { default as bgArt } from "./backgrounds/bg_art.png"
export { default as bgHero } from "./backgrounds/bg_street.png"

export { default as logoDark } from "./logos/dark_logo.svg"
export { default as logoLight } from "./logos/light_logo.svg"
export { default as logoUepb } from "./logos/uepb_logo.png"
export { default as logoUepbDark } from "./logos/uepb_dark_logo.png"
export { default as logoConedu } from "./logos/conedu_logo.webp"
export { default as logoConeduDark } from "./logos/conedu_dark_logo.webp"
export { default as logoGhostPipe } from "./logos/ghostpipe_completed_logo.png"
export { default as logoGhostPipeDark } from "./logos/ghostpipe_dark_completed_logo.png"

export { default as logoGmail } from "./envelope-regular.svg"
export { default as logoInstagram } from "./instagram-brands-solid.svg"

export { default as logoDnD } from "./systems/d&d.png"
export { default as logoCallOfCthulhu } from "./systems/coc.png"
export { default as logoTormenta20 } from "./systems/tormenta20.png"
export { default as logoOrdemParanormal } from "./systems/op.png"
export { default as logoOrdemParanormalDark } from "./systems/op_dark_mode.png"
export { default as logoKaos } from "./systems/kaos.png"
export { default as logoKaosDark } from "./systems/kaos_dark_mode.png"
